name: fluxoflutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  uuid: ^3.0.7
  flutter_material_color_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
